# Alarm
- platform: manual
  name: 'Robot Home'
  code: !secret 'alarm_pin'
  pending_time: 60
  delay_time: 60
  trigger_time: 4
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 0
    delay_time: 0
    trigger_time: 1
