# Sensors, sensors.yaml

# Time
# - platform: time_date
#   display_options:
#    - time

# Speedtest
- platform: speedtest
  monitored_conditions:
    - ping
    - download

# DarkSky weather
- platform: darksky
  api_key: !secret "darksky_api_key"
  monitored_conditions:
    - temperature

# System monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: '/'
    - type: processor_use
