# Switches
- platform: tplink
  host: !secret "audio_receiver_ip"
  name: "Audio Receiver"

- platform: tplink
  host: !secret "kid_club_lights_ip"
  name: "Kid Club Lights"

- platform: zoneminder
  command_on: 'Modect'
  command_off: 'Monitor'
