# Switches
- platform: tplink
  host: !secret "audio_receiver_ip"
  name: "Audio Receiver"

- platform: tplink
  host: !secret "holiday_lights_ip"
  name: "Holiday Lights"

- platform: zoneminder
  command_on: 'Modect'
  command_off: 'Monitor'
