title: Home
views:
  - title: Home
    icon: mdi:home
    cards:
      - type: entities
        title: Family
        show_header_toggle: false 
        entities:
          - device_tracker.cr_iphone
          - device_tracker.teris_iphone
      - type: entities
        title: Home Alarm Sensors
        show_header_toggle: false
        entities:
          - binary_sensor.front__garage_doors
          - binary_sensor.patio_doors
          - binary_sensor.ground_floor_windows
          - binary_sensor.mbr_windows
          - binary_sensor.upstairs_windows
      - type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - switch.audio_receiver
          - switch.holiday_lights
      - type: weather-forecast
        entity: weather.dark_sky
  - title: Cameras
    icon: mdi:camera
    cards:
      - type: vertical-stack
        cards:
          - type: picture-entity
            title: 'Front Door'
            entity: camera.front_door
            camera_image: camera.front_door
            show_state: false
          - type: picture-entity
            title: 'Back Door'
            entity: camera.back_door
            camera_image: camera.back_door
            show_state: false
          - type: horizontal-stack
            cards:
              - type: picture-entity
                title: 'Garage 2'
                entity: camera.garage_2
                camera_image: camera.garage_2
                show_state: false
              - type: picture-entity
                title: 'Garage 1'
                entity: camera.garage_1
                camera_image: camera.garage_1
                show_state: false
