title: 'Home'
views:
  - title: 'Home'
    icon: mdi:home
    cards:
      - type: entities
        title: 'Family'
        show_header_toggle: false 
        entities:
          - device_tracker.cr_iphone
          - device_tracker.teris_iphone
      - type: entities
        title: 'Home Alarm Sensors'
        show_header_toggle: false
        entities:
          - binary_sensor.front__garage_doors
          - binary_sensor.patio_doors
          - binary_sensor.ground_floor_windows
          - binary_sensor.mbr_windows
          - binary_sensor.upstairs_windows
      - type: entities
        title: 'Power Switches'
        show_header_toggle: false
        entities:
          - switch.audio_receiver
          - switch.holiday_lights
      - type: weather-forecast
        entity: weather.dark_sky
  - title: 'Cameras'
    icon: mdi:camera
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
            - type: picture-glance
              title: 'Front Door'
              entities:
              - switch.front_door_state
              camera_image: camera.front_door
            - type: picture-glance
              title: 'Living Room'
              entities:
              - switch.living_room_state
              camera_image: camera.living_room
          - type: horizontal-stack
            cards:
            - type: picture-glance
              title: 'Back Door'
              entities:
              - switch.back_door_state
              camera_image: camera.back_door
            - type: picture-glance
              title: 'Kid Club'
              entities:
              - switch.kid_club_state
              camera_image: camera.kid_club
          - type: horizontal-stack
            cards:
            - type: picture-glance
              title: 'Garage 1'
              entities:
              - switch.garage_1_state
              camera_image: camera.garage_1
            - type: picture
              image: '/local/black.jpg'

