#----------------------------------------------------------------------------
title: 'Home'
#----------------------------------------------------------------------------
views:
  - title: 'Home'
    icon: mdi:home
    cards:
      - type: glance
        title: 'Family'
        show_header_toggle: false 
        entities:
          - device_tracker.cr_iphone
          - device_tracker.teris_iphone
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: 'Power Switches'
        show_header_toggle: false
        entities:
          - switch.audio_receiver
          - switch.kid_club_lights
      - type: gauge
        title: 'CPU Load'
        unit: '%'
        entity: sensor.processor_use
        severity:
          green: 0
          yellow: 45
          red: 85
#      - type: gauge
#        title: 'Fast Speed'
#        entity: sensor.fast_com_download
#        min: 0
#        max: 120
      - type: glance
        title: 'Next Trash Pickup'
        show_header_toggle: false 
        entities:
          - sensor.next_trash_pickup
      - type: map
        # aspect_ratio: 16:9
        # default_zoom: 8
        entities:
          - device_tracker.cr_iphone
          - device_tracker.teris_iphone
          - zone.home
#----------------------------------------------------------------------------
  - title: 'Home Alarm'
#----------------------------------------------------------------------------
    icon: mdi:security
    cards:
      - type: alarm-panel
        name: 'Robot Home'
        entity: alarm_control_panel.robot_home
        states:
          - arm_home
          - arm_away
          - arm_night
      - type: entities
        title: 'Alarm Sensors'
        show_header_toggle: false
        entities:
          - binary_sensor.front_doors
          - binary_sensor.patio_doors
          - binary_sensor.ground_floor_windows
          - binary_sensor.mbr_windows
          - binary_sensor.upstairs_windows
#----------------------------------------------------------------------------
  - title: 'Cameras'
#----------------------------------------------------------------------------
    icon: mdi:camera
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
            - type: picture-glance
              title: 'Front Door'
              entities:
              - switch.front_door_state
              camera_image: camera.front_door
            - type: picture-glance
              title: 'Living Room'
              entities:
              - switch.living_room_state
              camera_image: camera.living_room
          - type: horizontal-stack
            cards:
            - type: picture-glance
              title: 'Back Door'
              entities:
              - switch.back_door_state
              camera_image: camera.back_door
            - type: picture-glance
              title: 'Kid Club'
              entities:
              - switch.kid_club_state
              camera_image: camera.kid_club
          - type: horizontal-stack
            cards:
            - type: picture-glance
              title: 'Garage 1'
              entities:
              - switch.garage_1_state
              camera_image: camera.garage_1
            - type: picture
              image: '/local/black.jpg'
#----------------------------------------------------------------------------
